# Generated by Django 3.1.14 on 2024-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
