# Generated by Django 3.1.14 on 2024-07-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='image',
            new_name='img_url',
        ),
    ]
