# Generated by Django 3.1.14 on 2024-07-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20240714_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='img_url',
            new_name='image',
        ),
    ]
